// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTBaseRoleList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTBaseRoleList GetRootAsDTBaseRoleList(ByteBuffer _bb) { return GetRootAsDTBaseRoleList(_bb, new DTBaseRoleList()); }
  public static DTBaseRoleList GetRootAsDTBaseRoleList(ByteBuffer _bb, DTBaseRoleList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTBaseRoleList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTBaseRole? DTBaseRoles(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTBaseRole?)(new YouYou.DataTable.DTBaseRole()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTBaseRolesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTBaseRoleList> CreateDTBaseRoleList(FlatBufferBuilder builder,
      VectorOffset DTBaseRolesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTBaseRoleList.AddDTBaseRoles(builder, DTBaseRolesOffset);
    return DTBaseRoleList.EndDTBaseRoleList(builder);
  }

  public static void StartDTBaseRoleList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTBaseRoles(FlatBufferBuilder builder, VectorOffset DTBaseRolesOffset) { builder.AddOffset(0, DTBaseRolesOffset.Value, 0); }
  public static VectorOffset CreateDTBaseRolesVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTBaseRole>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTBaseRolesVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTBaseRole>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTBaseRolesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTBaseRoleList> EndDTBaseRoleList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTBaseRoleList>(o);
  }
};


}
