// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTBaseMonsterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTBaseMonsterList GetRootAsDTBaseMonsterList(ByteBuffer _bb) { return GetRootAsDTBaseMonsterList(_bb, new DTBaseMonsterList()); }
  public static DTBaseMonsterList GetRootAsDTBaseMonsterList(ByteBuffer _bb, DTBaseMonsterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTBaseMonsterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTBaseMonster? DTBaseMonsters(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTBaseMonster?)(new YouYou.DataTable.DTBaseMonster()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTBaseMonstersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTBaseMonsterList> CreateDTBaseMonsterList(FlatBufferBuilder builder,
      VectorOffset DTBaseMonstersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTBaseMonsterList.AddDTBaseMonsters(builder, DTBaseMonstersOffset);
    return DTBaseMonsterList.EndDTBaseMonsterList(builder);
  }

  public static void StartDTBaseMonsterList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTBaseMonsters(FlatBufferBuilder builder, VectorOffset DTBaseMonstersOffset) { builder.AddOffset(0, DTBaseMonstersOffset.Value, 0); }
  public static VectorOffset CreateDTBaseMonstersVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTBaseMonster>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTBaseMonstersVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTBaseMonster>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTBaseMonstersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTBaseMonsterList> EndDTBaseMonsterList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTBaseMonsterList>(o);
  }
};


}
