// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTFontColorList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTFontColorList GetRootAsDTFontColorList(ByteBuffer _bb) { return GetRootAsDTFontColorList(_bb, new DTFontColorList()); }
  public static DTFontColorList GetRootAsDTFontColorList(ByteBuffer _bb, DTFontColorList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTFontColorList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTFontColor? DTFontColors(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTFontColor?)(new YouYou.DataTable.DTFontColor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTFontColorsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTFontColorList> CreateDTFontColorList(FlatBufferBuilder builder,
      VectorOffset DTFontColorsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTFontColorList.AddDTFontColors(builder, DTFontColorsOffset);
    return DTFontColorList.EndDTFontColorList(builder);
  }

  public static void StartDTFontColorList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTFontColors(FlatBufferBuilder builder, VectorOffset DTFontColorsOffset) { builder.AddOffset(0, DTFontColorsOffset.Value, 0); }
  public static VectorOffset CreateDTFontColorsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTFontColor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTFontColorsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTFontColor>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTFontColorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTFontColorList> EndDTFontColorList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTFontColorList>(o);
  }
};


}
