// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTFontColor : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTFontColor GetRootAsDTFontColor(ByteBuffer _bb) { return GetRootAsDTFontColor(_bb, new DTFontColor()); }
  public static DTFontColor GetRootAsDTFontColor(ByteBuffer _bb, DTFontColor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTFontColor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public int Rtest { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Gtest { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Btest { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Atest { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<YouYou.DataTable.DTFontColor> CreateDTFontColor(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset NameOffset = default(StringOffset),
      int Rtest = 0,
      int Gtest = 0,
      int Btest = 0,
      int Atest = 0) {
    builder.StartTable(6);
    DTFontColor.AddAtest(builder, Atest);
    DTFontColor.AddBtest(builder, Btest);
    DTFontColor.AddGtest(builder, Gtest);
    DTFontColor.AddRtest(builder, Rtest);
    DTFontColor.AddName(builder, NameOffset);
    DTFontColor.AddId(builder, Id);
    return DTFontColor.EndDTFontColor(builder);
  }

  public static void StartDTFontColor(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static void AddRtest(FlatBufferBuilder builder, int Rtest) { builder.AddInt(2, Rtest, 0); }
  public static void AddGtest(FlatBufferBuilder builder, int Gtest) { builder.AddInt(3, Gtest, 0); }
  public static void AddBtest(FlatBufferBuilder builder, int Btest) { builder.AddInt(4, Btest, 0); }
  public static void AddAtest(FlatBufferBuilder builder, int Atest) { builder.AddInt(5, Atest, 0); }
  public static Offset<YouYou.DataTable.DTFontColor> EndDTFontColor(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTFontColor>(o);
  }
};


}
