// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTGameLevelList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTGameLevelList GetRootAsDTGameLevelList(ByteBuffer _bb) { return GetRootAsDTGameLevelList(_bb, new DTGameLevelList()); }
  public static DTGameLevelList GetRootAsDTGameLevelList(ByteBuffer _bb, DTGameLevelList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTGameLevelList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTGameLevel? DTGameLevels(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTGameLevel?)(new YouYou.DataTable.DTGameLevel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTGameLevelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTGameLevelList> CreateDTGameLevelList(FlatBufferBuilder builder,
      VectorOffset DTGameLevelsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTGameLevelList.AddDTGameLevels(builder, DTGameLevelsOffset);
    return DTGameLevelList.EndDTGameLevelList(builder);
  }

  public static void StartDTGameLevelList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTGameLevels(FlatBufferBuilder builder, VectorOffset DTGameLevelsOffset) { builder.AddOffset(0, DTGameLevelsOffset.Value, 0); }
  public static VectorOffset CreateDTGameLevelsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTGameLevel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTGameLevelsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTGameLevel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTGameLevelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTGameLevelList> EndDTGameLevelList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTGameLevelList>(o);
  }
};


}
