// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTGameLevelRegion : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTGameLevelRegion GetRootAsDTGameLevelRegion(ByteBuffer _bb) { return GetRootAsDTGameLevelRegion(_bb, new DTGameLevelRegion()); }
  public static DTGameLevelRegion GetRootAsDTGameLevelRegion(ByteBuffer _bb, DTGameLevelRegion obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTGameLevelRegion __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int GameLevelId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RegionId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string InitSprite { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetInitSpriteBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetInitSpriteBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetInitSpriteArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<YouYou.DataTable.DTGameLevelRegion> CreateDTGameLevelRegion(FlatBufferBuilder builder,
      int Id = 0,
      int GameLevelId = 0,
      int RegionId = 0,
      StringOffset InitSpriteOffset = default(StringOffset)) {
    builder.StartTable(4);
    DTGameLevelRegion.AddInitSprite(builder, InitSpriteOffset);
    DTGameLevelRegion.AddRegionId(builder, RegionId);
    DTGameLevelRegion.AddGameLevelId(builder, GameLevelId);
    DTGameLevelRegion.AddId(builder, Id);
    return DTGameLevelRegion.EndDTGameLevelRegion(builder);
  }

  public static void StartDTGameLevelRegion(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddGameLevelId(FlatBufferBuilder builder, int GameLevelId) { builder.AddInt(1, GameLevelId, 0); }
  public static void AddRegionId(FlatBufferBuilder builder, int RegionId) { builder.AddInt(2, RegionId, 0); }
  public static void AddInitSprite(FlatBufferBuilder builder, StringOffset InitSpriteOffset) { builder.AddOffset(3, InitSpriteOffset.Value, 0); }
  public static Offset<YouYou.DataTable.DTGameLevelRegion> EndDTGameLevelRegion(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTGameLevelRegion>(o);
  }
};


}
