// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTItemList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTItemList GetRootAsDTItemList(ByteBuffer _bb) { return GetRootAsDTItemList(_bb, new DTItemList()); }
  public static DTItemList GetRootAsDTItemList(ByteBuffer _bb, DTItemList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTItemList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTItem? DTItems(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTItem?)(new YouYou.DataTable.DTItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTItemList> CreateDTItemList(FlatBufferBuilder builder,
      VectorOffset DTItemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTItemList.AddDTItems(builder, DTItemsOffset);
    return DTItemList.EndDTItemList(builder);
  }

  public static void StartDTItemList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTItems(FlatBufferBuilder builder, VectorOffset DTItemsOffset) { builder.AddOffset(0, DTItemsOffset.Value, 0); }
  public static VectorOffset CreateDTItemsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTItemsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTItemList> EndDTItemList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTItemList>(o);
  }
};


}
