// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTRoleAnimationList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTRoleAnimationList GetRootAsDTRoleAnimationList(ByteBuffer _bb) { return GetRootAsDTRoleAnimationList(_bb, new DTRoleAnimationList()); }
  public static DTRoleAnimationList GetRootAsDTRoleAnimationList(ByteBuffer _bb, DTRoleAnimationList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTRoleAnimationList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTRoleAnimation? DTRoleAnimations(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTRoleAnimation?)(new YouYou.DataTable.DTRoleAnimation()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTRoleAnimationsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTRoleAnimationList> CreateDTRoleAnimationList(FlatBufferBuilder builder,
      VectorOffset DTRoleAnimationsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTRoleAnimationList.AddDTRoleAnimations(builder, DTRoleAnimationsOffset);
    return DTRoleAnimationList.EndDTRoleAnimationList(builder);
  }

  public static void StartDTRoleAnimationList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTRoleAnimations(FlatBufferBuilder builder, VectorOffset DTRoleAnimationsOffset) { builder.AddOffset(0, DTRoleAnimationsOffset.Value, 0); }
  public static VectorOffset CreateDTRoleAnimationsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTRoleAnimation>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTRoleAnimationsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTRoleAnimation>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTRoleAnimationsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTRoleAnimationList> EndDTRoleAnimationList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTRoleAnimationList>(o);
  }
};


}
