// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTRoleAnimCategoryList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTRoleAnimCategoryList GetRootAsDTRoleAnimCategoryList(ByteBuffer _bb) { return GetRootAsDTRoleAnimCategoryList(_bb, new DTRoleAnimCategoryList()); }
  public static DTRoleAnimCategoryList GetRootAsDTRoleAnimCategoryList(ByteBuffer _bb, DTRoleAnimCategoryList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTRoleAnimCategoryList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTRoleAnimCategory? DTRoleAnimCategorys(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTRoleAnimCategory?)(new YouYou.DataTable.DTRoleAnimCategory()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTRoleAnimCategorysLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTRoleAnimCategoryList> CreateDTRoleAnimCategoryList(FlatBufferBuilder builder,
      VectorOffset DTRoleAnimCategorysOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTRoleAnimCategoryList.AddDTRoleAnimCategorys(builder, DTRoleAnimCategorysOffset);
    return DTRoleAnimCategoryList.EndDTRoleAnimCategoryList(builder);
  }

  public static void StartDTRoleAnimCategoryList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTRoleAnimCategorys(FlatBufferBuilder builder, VectorOffset DTRoleAnimCategorysOffset) { builder.AddOffset(0, DTRoleAnimCategorysOffset.Value, 0); }
  public static VectorOffset CreateDTRoleAnimCategorysVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTRoleAnimCategory>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTRoleAnimCategorysVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTRoleAnimCategory>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTRoleAnimCategorysVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTRoleAnimCategoryList> EndDTRoleAnimCategoryList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTRoleAnimCategoryList>(o);
  }
};


}
