// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTShopCategory : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTShopCategory GetRootAsDTShopCategory(ByteBuffer _bb) { return GetRootAsDTShopCategory(_bb, new DTShopCategory()); }
  public static DTShopCategory GetRootAsDTShopCategory(ByteBuffer _bb, DTShopCategory obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTShopCategory __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<YouYou.DataTable.DTShopCategory> CreateDTShopCategory(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset NameOffset = default(StringOffset)) {
    builder.StartTable(2);
    DTShopCategory.AddName(builder, NameOffset);
    DTShopCategory.AddId(builder, Id);
    return DTShopCategory.EndDTShopCategory(builder);
  }

  public static void StartDTShopCategory(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(1, NameOffset.Value, 0); }
  public static Offset<YouYou.DataTable.DTShopCategory> EndDTShopCategory(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTShopCategory>(o);
  }
};


}
