// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSkillLevelList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTSkillLevelList GetRootAsDTSkillLevelList(ByteBuffer _bb) { return GetRootAsDTSkillLevelList(_bb, new DTSkillLevelList()); }
  public static DTSkillLevelList GetRootAsDTSkillLevelList(ByteBuffer _bb, DTSkillLevelList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSkillLevelList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTSkillLevel? DTSkillLevels(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTSkillLevel?)(new YouYou.DataTable.DTSkillLevel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTSkillLevelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTSkillLevelList> CreateDTSkillLevelList(FlatBufferBuilder builder,
      VectorOffset DTSkillLevelsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTSkillLevelList.AddDTSkillLevels(builder, DTSkillLevelsOffset);
    return DTSkillLevelList.EndDTSkillLevelList(builder);
  }

  public static void StartDTSkillLevelList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTSkillLevels(FlatBufferBuilder builder, VectorOffset DTSkillLevelsOffset) { builder.AddOffset(0, DTSkillLevelsOffset.Value, 0); }
  public static VectorOffset CreateDTSkillLevelsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSkillLevel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTSkillLevelsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSkillLevel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTSkillLevelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTSkillLevelList> EndDTSkillLevelList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTSkillLevelList>(o);
  }
};


}
