// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSys_SceneList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTSys_SceneList GetRootAsDTSys_SceneList(ByteBuffer _bb) { return GetRootAsDTSys_SceneList(_bb, new DTSys_SceneList()); }
  public static DTSys_SceneList GetRootAsDTSys_SceneList(ByteBuffer _bb, DTSys_SceneList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSys_SceneList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTSys_Scene? DTSysScenes(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTSys_Scene?)(new YouYou.DataTable.DTSys_Scene()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTSysScenesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTSys_SceneList> CreateDTSys_SceneList(FlatBufferBuilder builder,
      VectorOffset DTSys_ScenesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTSys_SceneList.AddDTSysScenes(builder, DTSys_ScenesOffset);
    return DTSys_SceneList.EndDTSys_SceneList(builder);
  }

  public static void StartDTSys_SceneList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTSysScenes(FlatBufferBuilder builder, VectorOffset DTSysScenesOffset) { builder.AddOffset(0, DTSysScenesOffset.Value, 0); }
  public static VectorOffset CreateDTSysScenesVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_Scene>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTSysScenesVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_Scene>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTSysScenesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTSys_SceneList> EndDTSys_SceneList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTSys_SceneList>(o);
  }
};


}
