// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSys_EffectList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTSys_EffectList GetRootAsDTSys_EffectList(ByteBuffer _bb) { return GetRootAsDTSys_EffectList(_bb, new DTSys_EffectList()); }
  public static DTSys_EffectList GetRootAsDTSys_EffectList(ByteBuffer _bb, DTSys_EffectList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSys_EffectList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTSys_Effect? DTSysEffects(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTSys_Effect?)(new YouYou.DataTable.DTSys_Effect()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTSysEffectsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTSys_EffectList> CreateDTSys_EffectList(FlatBufferBuilder builder,
      VectorOffset DTSys_EffectsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTSys_EffectList.AddDTSysEffects(builder, DTSys_EffectsOffset);
    return DTSys_EffectList.EndDTSys_EffectList(builder);
  }

  public static void StartDTSys_EffectList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTSysEffects(FlatBufferBuilder builder, VectorOffset DTSysEffectsOffset) { builder.AddOffset(0, DTSysEffectsOffset.Value, 0); }
  public static VectorOffset CreateDTSysEffectsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_Effect>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTSysEffectsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_Effect>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTSysEffectsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTSys_EffectList> EndDTSys_EffectList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTSys_EffectList>(o);
  }
};


}
