// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSys_SceneDetailList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTSys_SceneDetailList GetRootAsDTSys_SceneDetailList(ByteBuffer _bb) { return GetRootAsDTSys_SceneDetailList(_bb, new DTSys_SceneDetailList()); }
  public static DTSys_SceneDetailList GetRootAsDTSys_SceneDetailList(ByteBuffer _bb, DTSys_SceneDetailList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSys_SceneDetailList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTSys_SceneDetail? DTSysSceneDetails(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTSys_SceneDetail?)(new YouYou.DataTable.DTSys_SceneDetail()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTSysSceneDetailsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTSys_SceneDetailList> CreateDTSys_SceneDetailList(FlatBufferBuilder builder,
      VectorOffset DTSys_SceneDetailsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTSys_SceneDetailList.AddDTSysSceneDetails(builder, DTSys_SceneDetailsOffset);
    return DTSys_SceneDetailList.EndDTSys_SceneDetailList(builder);
  }

  public static void StartDTSys_SceneDetailList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTSysSceneDetails(FlatBufferBuilder builder, VectorOffset DTSysSceneDetailsOffset) { builder.AddOffset(0, DTSysSceneDetailsOffset.Value, 0); }
  public static VectorOffset CreateDTSysSceneDetailsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_SceneDetail>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTSysSceneDetailsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_SceneDetail>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTSysSceneDetailsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTSys_SceneDetailList> EndDTSys_SceneDetailList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTSys_SceneDetailList>(o);
  }
};


}
