// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSys_Effect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTSys_Effect GetRootAsDTSys_Effect(ByteBuffer _bb) { return GetRootAsDTSys_Effect(_bb, new DTSys_Effect()); }
  public static DTSys_Effect GetRootAsDTSys_Effect(ByteBuffer _bb, DTSys_Effect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSys_Effect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Desc { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDescBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescArray() { return __p.__vector_as_array<byte>(6); }
  public int PrefabId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float KeepTime { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int SoundId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<YouYou.DataTable.DTSys_Effect> CreateDTSys_Effect(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset DescOffset = default(StringOffset),
      int PrefabId = 0,
      float KeepTime = 0.0f,
      int SoundId = 0,
      int Type = 0) {
    builder.StartTable(6);
    DTSys_Effect.AddType(builder, Type);
    DTSys_Effect.AddSoundId(builder, SoundId);
    DTSys_Effect.AddKeepTime(builder, KeepTime);
    DTSys_Effect.AddPrefabId(builder, PrefabId);
    DTSys_Effect.AddDesc(builder, DescOffset);
    DTSys_Effect.AddId(builder, Id);
    return DTSys_Effect.EndDTSys_Effect(builder);
  }

  public static void StartDTSys_Effect(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddDesc(FlatBufferBuilder builder, StringOffset DescOffset) { builder.AddOffset(1, DescOffset.Value, 0); }
  public static void AddPrefabId(FlatBufferBuilder builder, int PrefabId) { builder.AddInt(2, PrefabId, 0); }
  public static void AddKeepTime(FlatBufferBuilder builder, float KeepTime) { builder.AddFloat(3, KeepTime, 0.0f); }
  public static void AddSoundId(FlatBufferBuilder builder, int SoundId) { builder.AddInt(4, SoundId, 0); }
  public static void AddType(FlatBufferBuilder builder, int Type) { builder.AddInt(5, Type, 0); }
  public static Offset<YouYou.DataTable.DTSys_Effect> EndDTSys_Effect(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTSys_Effect>(o);
  }
};


}
