// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSys_StorySoundList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTSys_StorySoundList GetRootAsDTSys_StorySoundList(ByteBuffer _bb) { return GetRootAsDTSys_StorySoundList(_bb, new DTSys_StorySoundList()); }
  public static DTSys_StorySoundList GetRootAsDTSys_StorySoundList(ByteBuffer _bb, DTSys_StorySoundList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSys_StorySoundList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTSys_StorySound? DTSysStorySounds(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTSys_StorySound?)(new YouYou.DataTable.DTSys_StorySound()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTSysStorySoundsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTSys_StorySoundList> CreateDTSys_StorySoundList(FlatBufferBuilder builder,
      VectorOffset DTSys_StorySoundsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTSys_StorySoundList.AddDTSysStorySounds(builder, DTSys_StorySoundsOffset);
    return DTSys_StorySoundList.EndDTSys_StorySoundList(builder);
  }

  public static void StartDTSys_StorySoundList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTSysStorySounds(FlatBufferBuilder builder, VectorOffset DTSysStorySoundsOffset) { builder.AddOffset(0, DTSysStorySoundsOffset.Value, 0); }
  public static VectorOffset CreateDTSysStorySoundsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_StorySound>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTSysStorySoundsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTSys_StorySound>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTSysStorySoundsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTSys_StorySoundList> EndDTSys_StorySoundList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTSys_StorySoundList>(o);
  }
};


}
