// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace YouYou.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTWorldMapList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DTWorldMapList GetRootAsDTWorldMapList(ByteBuffer _bb) { return GetRootAsDTWorldMapList(_bb, new DTWorldMapList()); }
  public static DTWorldMapList GetRootAsDTWorldMapList(ByteBuffer _bb, DTWorldMapList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTWorldMapList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public YouYou.DataTable.DTWorldMap? DTWorldMaps(int j) { int o = __p.__offset(4); return o != 0 ? (YouYou.DataTable.DTWorldMap?)(new YouYou.DataTable.DTWorldMap()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTWorldMapsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<YouYou.DataTable.DTWorldMapList> CreateDTWorldMapList(FlatBufferBuilder builder,
      VectorOffset DTWorldMapsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTWorldMapList.AddDTWorldMaps(builder, DTWorldMapsOffset);
    return DTWorldMapList.EndDTWorldMapList(builder);
  }

  public static void StartDTWorldMapList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTWorldMaps(FlatBufferBuilder builder, VectorOffset DTWorldMapsOffset) { builder.AddOffset(0, DTWorldMapsOffset.Value, 0); }
  public static VectorOffset CreateDTWorldMapsVector(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTWorldMap>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTWorldMapsVectorBlock(FlatBufferBuilder builder, Offset<YouYou.DataTable.DTWorldMap>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDTWorldMapsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<YouYou.DataTable.DTWorldMapList> EndDTWorldMapList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<YouYou.DataTable.DTWorldMapList>(o);
  }
};


}
